### ISSUE TITLE
cmdTau logging: indices instead of names

### ISSUE THREAD

**Issue by rohanpsingh** [jrl-umi3218/mc_openrtm#29]
Why in the case of `cmdTau`, `mc_log_ui` does not automatically convert the joint indices to joint names? In the case of most other quantities, `qIn`, `qOut` and even entries created by my controller are automatically converted.

https://github.com/jrl-umi3218/mc_openrtm/blob/b2a28aaff697945f3d36dddcba09cfc4dc2b7cb1/src/MCControl.cpp#L669

**Comment by gergondet** [comment]
This only happens for a pre-defined set of prefixes defined here: https://github.com/jrl-umi3218/mc_rtc/blob/master/utils/mc_log_gui/mc_log_ui/mc_log_ui.py#L767

**Comment by rohanpsingh** [comment]
Fixed in https://github.com/jrl-umi3218/mc_openrtm/pull/31/commits/3f7df46308ea6cbdd5c3d1a1cfc337ef10df3030
