### ISSUE TITLE
URDF TO VRML model

### ISSUE THREAD

**Issue by 853734690** [jrl-umi3218/mc_openrtm#33]
Dear Sir,

I am new in Chereonoid  and  tying to integrate my robot in Chereonoid ,but I only have the URDF model . I tried to transform URDF to VRML model by using GrxUI witch is no longer in use and I failed in the end. So May I ask you how to finish it?

Thank you very much.

Sincerely,
Ethan

**Comment by gergondet** [comment]
Hi @853734690 

I think you can try [simtrans](https://github.com/fkanehiro/simtrans) for this although we have only used it in the opposite direction (VRML -> URDF)

**Comment by 853734690** [comment]
Thank You for your reply. 
I have try it and finish 
Thank You
Best Regards
